### ISSUE TITLE
Tunnels closed locally but left active on SauceLabs

### ISSUE THREAD

**Issue by LaurentGoderre** [axemclion/grunt-saucelabs#182]
I noticed that none of the tunnels created by this task get closed by the task, they only close several after the test. I am in Windows ( I don't know if it matters)

**Comment by gvas** [comment]
I've just noticed that, too. The problem is in the sauce-tunnel package, I've already sent a PR to them: jmreidy/sauce-tunnel#32

**Comment by LaurentGoderre** [comment]
Nice! Thanks!
