### ISSUE TITLE
Warning: Object.keys called on non-object Use --force to continue.

### ISSUE THREAD

**Issue by JFusco** [axemclion/grunt-saucelabs#183]
I am using this version of Grunt:
grunt-cli v0.1.13
grunt v0.4.5

I am using this version of saucelabs-grunt:
saucelabs-grunt v8.5.0

This version of NPM
npm v2.1.17

This version of Node
node v0.10.35

When I try to run a very simple test via grunt-saucelabs I am getting this error:
Warning: Object.keys called on non-object Use --force to continue.

Are you able to provide more feedback as to what this error might be?  If you need to see my configuration I will happily share it - or any other information I can provide.

Thanks,
- Joe

**Comment by Jonahss** [comment]
I've encountered this before, I think it's a general grunt thing. Check to make sure you're declaring the proper task names?

**Comment by Jonahss** [comment]
Closed due to inactivity. Were you able to resolve this issue?

**Comment by JFusco** [comment]
Yes I was, thanks for checking back! - just grunt strangeness
