### ISSUE TITLE
repo description is misleading

### ISSUE THREAD

**Issue by patrickkettner** [axemclion/grunt-saucelabs#185]
![image](https://cloud.githubusercontent.com/assets/465414/6273811/640f2600-b840-11e4-9ef6-00b088b8b093.png)

its so much more than that :]

**Comment by Jonahss** [comment]
too true. I think only @axemclion has permissions to change it ^.^

**Comment by axemclion** [comment]
What do you want me to change it to - the repo has indeed come a long way from where I started it !! - thanks to @Jonahss

**Comment by patrickkettner** [comment]
simplest thing would be to drop `qunit`. 

maybe "Grunt task for running all your browser tests using Sauce Labs"?

**Comment by axemclion** [comment]
done

**Comment by patrickkettner** [comment]
beaut!
