### ISSUE TITLE
Travis Sauce Connect Addon Integration

### ISSUE THREAD

**Issue by stdavis** [axemclion/grunt-saucelabs#202]
Is there any documented way for this project to work with the new [sauce connect addon for travis](https://docs.travis-ci.com/user/sauce-connect/)?

Wondering if I should be passing `tunneled: false` or something?

**Comment by Jonahss** [comment]
This sounds like a question for @halkeye . What do you think @halkeye?

**Comment by halkeye** [comment]
I'm sorry, I haven't had a chance to look at our travis integration yet. I'm not sure what you mean by work though.

from the documentation on both sides, I'd think you'd want:
`tunneled: false` and your tests would make sure they use the cap/identifier `'tunnel-identifier': ENV['TRAVIS_JOB_NUMBER']`

**Comment by stdavis** [comment]
Thanks for the advice. I had already tried your suggestion, @halkeye, to no avail. I'm currently working on converting all of my unit tests to run through intern so that I don't have to worry about the conflict between this project and intern. Thanks anyways.
