### ISSUE TITLE
Grunt 1.0.x support

### ISSUE THREAD

**Issue by evilaliv3** [axemclion/grunt-saucelabs#210]
The module fails to install with Grunt 1.0.x. Are there plans to bring support to the newest version? 

Thanks for all the hard work!

Since months all the grunt plugins are moving to use grunt 1.0.1 that is the current stable version while the 0.4.5 is now going to be considered outdated.

**Comment by evilaliv3** [comment]
AFAICT, the module works with the latest Grunt. The only issue is that the requirement is in the form

```
"dependencies": {
    ...
    "grunt": "^0.4.1",
    ...
}
```

I think it should be ">=0.4.1", because, as it is, it requires to download an obsolete (and useless) version of grunt just to please the dependency resolver.

**Comment by evilaliv3** [comment]
Ah actually commit https://github.com/axemclion/grunt-saucelabs/commit/2159acc63389db67b5a00b1eb625d519002498a2 already fixed the issue.

Whould it be possible to have a the package released soon?

**Comment by Jonahss** [comment]
Doing it ^.^

Sorry you had to wait.

**Comment by Jonahss** [comment]
Published 8.6.3
